// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title  VaccineRegistry
 * @author AgentGuardian Protocol
 * @notice Layer 6B — Vaccine Proof System
 *         "Every attack makes the network harder to attack."
 *
 * ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  WHAT THIS CONTRACT DOES                                                ║
 * ║                                                                          ║
 * ║  When an agent is slashed, its decisionHash (the Poseidon hash of its   ║
 * ║  ReLU activation outputs from relu.circom) is registered here as a      ║
 * ║  "bad cognition fingerprint." This fingerprint becomes a permanent entry ║
 * ║  in the Vaccine Blacklist — an off-chain Sparse Merkle Tree whose root  ║
 * ║  is stored and updated on-chain.                                         ║
 * ║                                                                          ║
 * ║  Before any future agent transaction is approved by CognitionVerifier,  ║
 * ║  the agent must prove — via a ZK non-membership proof (vaccine.circom)  ║
 * ║  — that their current decisionHash is NOT in the blacklist.             ║
 * ║                                                                          ║
 * ║  This creates a SELF-IMMUNISING NETWORK:                                ║
 * ║    • Attack happens → fingerprint extracted → blacklist updated          ║
 * ║    • Every future agent must prove they don't match any past attack      ║
 * ║    • The more attacks, the stronger the immunity                         ║
 * ║    • Zero knowledge: agents never learn what the blacklisted hashes are ║
 * ║                                                                          ║
 * ╠══════════════════════════════════════════════════════════════════════════╣
 * ║  BEYOND-STATE-OF-THE-ART FEATURES                                       ║
 * ║                                                                          ║
 * ║  1. CONTEXT-AWARE FINGERPRINTING                                         ║
 * ║     Blacklisted entry = Poseidon(decisionHash, contextHash) where        ║
 * ║     contextHash = Poseidon(recipient, amount, chainId). A cognition      ║
 * ║     pattern that was malicious in one context isn't auto-flagged in a   ║
 * ║     different context. Prevents false positives across agent populations.║
 * ║                                                                          ║
 * ║  2. SEVERITY-TIERED BLACKLISTING                                         ║
 * ║     Not all slashes are equal. Minor slashes add fingerprints to the    ║
 * ║     "soft" blacklist (warning-level, non-blocking). Severe slashes add  ║
 * ║     to the "hard" blacklist (blocking, ZK proof required). Agents near  ║
 * ║     a soft-blacklisted hash receive a reputation warning.               ║
 * ║                                                                          ║
 * ║  3. FINGERPRINT EXPIRY                                                   ║
 * ║     Each fingerprint has a TTL (default: 365 days). Expired fingerprints║
 * ║     are prunable from the SMT, allowing the tree to shrink. This        ║
 * ║     prevents unbounded SMT growth and mirrors real-world parole systems. ║
 * ║     Prune via off-chain keeper → updateRoot() with new post-prune root.  ║
 * ║                                                                          ║
 * ║  4. MULTI-BLACKLIST SUPPORT                                              ║
 * ║     Three independent SMT roots: HARD (blocking), SOFT (warning),       ║
 * ║     and RESEARCH (analytics-only, not enforced). The research list       ║
 * ║     accumulates all slashed hashes for pattern analysis even if they    ║
 * ║     later expire from the hard list.                                     ║
 * ║                                                                          ║
 * ║  5. CROSS-CHAIN ROOT SYNCHRONISATION HOOK                               ║
 * ║     When a new fingerprint is added, _emitCrossChainSync() fires.       ║
 * ║     Layer 6C (CrossChainIdentity.sol / sentinel.ts) listens and         ║
 * ║     propagates the new root to all registered destination chains via     ║
 * ║     LayerZero. Every chain gets the same blacklist simultaneously.      ║
 * ║                                                                          ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 */

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";

// ─── Interfaces ───────────────────────────────────────────────────────────────

interface IVaccineVerifier {
    /**
     * @dev Groth16 verifier for vaccine.circom (non-membership proof).
     *      Auto-generated by: snarkjs zkey export solidityverifier vaccine_final.zkey
     *      Public inputs: [blacklistRoot, decisionHash]
     */
    function verifyProof(
        uint256[2]  calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2]  calldata _pC,
        uint256[2]  calldata _pubSignals
    ) external view returns (bool);
}

interface IAgentRegistry {
    function getReputation(uint256 tokenId) external view returns (uint256);
    function updateReputation(uint256 tokenId, int256 delta) external;
    function ownerOf(uint256 tokenId) external view returns (address);
}

// ─── VaccineRegistry ──────────────────────────────────────────────────────────

contract VaccineRegistry is Ownable, ReentrancyGuard, Pausable {

    // ═══════════════════════════════════════════════════════════════════════
    //  CONSTANTS
    // ═══════════════════════════════════════════════════════════════════════

    /// @notice SMT depth — matches vaccine.circom template VaccineProof(20)
    uint256 public constant SMT_DEPTH = 20;

    /// @notice Maximum blacklist entries before mandatory pruning
    uint256 public constant MAX_BLACKLIST_SIZE = 1_000_000; // 2^20 leaves

    /// @notice Default TTL for a fingerprint entry (365 days)
    uint256 public constant DEFAULT_FINGERPRINT_TTL = 365 days;

    /// @notice Minimum TTL — cannot expire a fresh fingerprint prematurely
    uint256 public constant MIN_FINGERPRINT_TTL = 7 days;

    /// @notice Hard slash threshold: slash > this amount triggers hard blacklisting
    uint256 public constant HARD_SLASH_THRESHOLD = 10_000e18; // 10k rAGNT

    // ═══════════════════════════════════════════════════════════════════════
    //  BLACKLIST TIERS
    // ═══════════════════════════════════════════════════════════════════════

    enum BlacklistTier {
        NONE,       // Not blacklisted
        SOFT,       // Warning-level: reputation penalty, not blocking
        HARD,       // Blocking: ZK non-membership proof required
        PERMANENT   // Irreversible: created only by governance vote
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  STATE
    // ═══════════════════════════════════════════════════════════════════════

    IVaccineVerifier public vaccineVerifier;
    IAgentRegistry   public agentRegistry;

    // ── SMT Roots (one per tier) ──────────────────────────────────────────

    /// @notice Current root of the HARD blacklist SMT — agents must prove non-membership
    uint256 public hardBlacklistRoot;

    /// @notice Current root of the SOFT blacklist SMT — for reputation warnings only
    uint256 public softBlacklistRoot;

    /// @notice Research list root — analytics only, never enforced
    uint256 public researchBlacklistRoot;

    /// @notice Root update nonce — prevents stale proof replay across root updates
    uint256 public rootUpdateNonce;

    // ── Fingerprint registry ──────────────────────────────────────────────

    struct FingerprintEntry {
        uint256 decisionHash;        // Poseidon(post[0..7]) from relu.circom
        uint256 contextHash;         // Poseidon(recipient, amount, chainId) — context binding
        uint256 compositeKey;        // Poseidon(decisionHash, contextHash) — the actual SMT key
        uint256 slashedAgentTokenId; // Which agent produced this fingerprint
        uint256 slashAmount;         // How much was slashed (determines tier)
        uint256 registeredAt;        // Timestamp of registration
        uint256 expiresAt;           // Timestamp of expiry (0 = permanent)
        BlacklistTier tier;          // SOFT / HARD / PERMANENT
        bool expired;                // True if pruned from active SMT
    }

    /// @notice compositeKey → FingerprintEntry
    mapping(uint256 => FingerprintEntry) public fingerprints;

    /// @notice Array of all composite keys (for enumeration and pruning)
    uint256[] public allFingerprintKeys;

    /// @notice Hard blacklist size (active, non-expired entries)
    uint256 public hardBlacklistSize;

    /// @notice Soft blacklist size
    uint256 public softBlacklistSize;

    // ── Used proofs nullifier set ─────────────────────────────────────────
    // Prevents the same ZK non-membership proof from being reused across
    // multiple transactions. Each proof is single-use.

    /// @notice keccak256(proofBytes) → used (replay protection)
    mapping(bytes32 => bool) public usedVaccineProofs;

    // ── Authorized callers ────────────────────────────────────────────────

    /// @notice Only these addresses can register new fingerprints
    mapping(address => bool) public authorizedRegistrars;

    // ═══════════════════════════════════════════════════════════════════════
    //  EVENTS
    // ═══════════════════════════════════════════════════════════════════════

    event FingerprintRegistered(
        uint256 indexed compositeKey,
        uint256 indexed decisionHash,
        uint256 indexed slashedAgentTokenId,
        BlacklistTier tier,
        uint256 slashAmount,
        uint256 expiresAt
    );

    event BlacklistRootUpdated(
        BlacklistTier indexed tier,
        uint256 oldRoot,
        uint256 newRoot,
        uint256 nonce,
        uint256 blacklistSize
    );

    event VaccineProofVerified(
        address indexed agent,
        uint256 indexed decisionHash,
        uint256 blacklistRoot,
        bytes32 proofNullifier
    );

    event VaccineProofRejected(
        address indexed agent,
        uint256 indexed decisionHash,
        string reason
    );

    event FingerprintExpired(
        uint256 indexed compositeKey,
        uint256 indexed decisionHash,
        BlacklistTier tier
    );

    /// @notice Fired when a new fingerprint triggers cross-chain sync (Layer 6C hook)
    event CrossChainSyncRequired(
        BlacklistTier indexed tier,
        uint256 newRoot,
        uint256 fingerprintCount,
        bytes32 syncId
    );

    // ═══════════════════════════════════════════════════════════════════════
    //  ERRORS
    // ═══════════════════════════════════════════════════════════════════════

    error InvalidProof();
    error ProofAlreadyUsed(bytes32 nullifier);
    error RootMismatch(uint256 providedRoot, uint256 currentRoot);
    error FingerprintAlreadyExists(uint256 compositeKey);
    error BlacklistFull();
    error UnauthorizedRegistrar(address caller);
    error ZeroDecisionHash();
    error InvalidTTL(uint256 ttl, uint256 minimum);
    error FingerprintNotFound(uint256 compositeKey);
    error PermanentFingerprintCannotExpire(uint256 compositeKey);

    // ═══════════════════════════════════════════════════════════════════════
    //  CONSTRUCTOR
    // ═══════════════════════════════════════════════════════════════════════

    constructor(
        address _vaccineVerifier,
        address _agentRegistry
    ) Ownable(msg.sender) {
        vaccineVerifier = IVaccineVerifier(_vaccineVerifier);
        agentRegistry   = IAgentRegistry(_agentRegistry);

        // Initial SMT roots are 0 (empty trees)
        // An empty SMT with Poseidon hashing has root = 0
        // Any agent can trivially prove non-membership against an empty tree
        // (i.e., before any agent has been slashed, all agents pass for free)
        hardBlacklistRoot     = 0;
        softBlacklistRoot     = 0;
        researchBlacklistRoot = 0;
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  MODIFIERS
    // ═══════════════════════════════════════════════════════════════════════

    modifier onlyAuthorizedRegistrar() {
        if (!authorizedRegistrars[msg.sender] && msg.sender != owner()) {
            revert UnauthorizedRegistrar(msg.sender);
        }
        _;
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  FINGERPRINT REGISTRATION
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * @notice  Register a slashed agent's cognition fingerprint into the blacklist.
     * @dev     Called by UnderwriterDAO (after slash) or AgentGuardian (after block).
     *          The composite key = Poseidon(decisionHash, contextHash) prevents
     *          false positives: same neural pattern in a different context is NOT
     *          automatically malicious.
     *
     *          TIER DETERMINATION:
     *          - slashAmount > HARD_SLASH_THRESHOLD → HARD (blocks future txs)
     *          - slashAmount <= HARD_SLASH_THRESHOLD → SOFT (reputation warning only)
     *          - Governance vote → PERMANENT (irreversible)
     *
     * @param decisionHash        Poseidon(post[0..7]) from relu.circom public output
     * @param contextHash         Poseidon(recipient, amount, chainId) of the bad tx
     * @param slashedAgentTokenId The agent that was slashed
     * @param slashAmount         Amount slashed (determines tier)
     * @param customTTL           Custom TTL in seconds (0 = use DEFAULT_FINGERPRINT_TTL)
     */
    function registerFingerprint(
        uint256 decisionHash,
        uint256 contextHash,
        uint256 slashedAgentTokenId,
        uint256 slashAmount,
        uint256 customTTL
    )
        external
        onlyAuthorizedRegistrar
        whenNotPaused
        nonReentrant
        returns (uint256 compositeKey)
    {
        if (decisionHash == 0) revert ZeroDecisionHash();
        if (hardBlacklistSize >= MAX_BLACKLIST_SIZE) revert BlacklistFull();

        // Composite key: Poseidon(decisionHash, contextHash)
        // Context-binding prevents cross-context false positives
        compositeKey = _poseidon2(decisionHash, contextHash);

        if (fingerprints[compositeKey].registeredAt != 0) {
            revert FingerprintAlreadyExists(compositeKey);
        }

        // Determine tier based on slash severity
        BlacklistTier tier = slashAmount > HARD_SLASH_THRESHOLD
            ? BlacklistTier.HARD
            : BlacklistTier.SOFT;

        uint256 ttl = customTTL == 0 ? DEFAULT_FINGERPRINT_TTL : customTTL;
        if (ttl < MIN_FINGERPRINT_TTL) revert InvalidTTL(ttl, MIN_FINGERPRINT_TTL);

        uint256 expiresAt = block.timestamp + ttl;

        fingerprints[compositeKey] = FingerprintEntry({
            decisionHash:        decisionHash,
            contextHash:         contextHash,
            compositeKey:        compositeKey,
            slashedAgentTokenId: slashedAgentTokenId,
            slashAmount:         slashAmount,
            registeredAt:        block.timestamp,
            expiresAt:           expiresAt,
            tier:                tier,
            expired:             false
        });

        allFingerprintKeys.push(compositeKey);

        if (tier == BlacklistTier.HARD) hardBlacklistSize++;
        else softBlacklistSize++;

        // Apply reputation penalty to the slashed agent
        // Even after slash, reputation continues to decay via fingerprint registration
        agentRegistry.updateReputation(slashedAgentTokenId, -50);

        emit FingerprintRegistered(
            compositeKey,
            decisionHash,
            slashedAgentTokenId,
            tier,
            slashAmount,
            expiresAt
        );

        // Trigger cross-chain synchronisation (Layer 6C hook)
        // VaccineManager.ts listens for this event and calls sentinel.ts
        _emitCrossChainSync(tier);

        return compositeKey;
    }

    /**
     * @notice  Register a PERMANENT fingerprint (requires governance / multisig).
     * @dev     Permanent fingerprints cannot expire. Used only for the most severe
     *          violations (e.g., agent attempted to drain InsurancePool entirely).
     *          Bypasses TTL mechanism entirely.
     */
    function registerPermanentFingerprint(
        uint256 decisionHash,
        uint256 contextHash,
        uint256 slashedAgentTokenId
    )
        external
        onlyOwner
        whenNotPaused
        nonReentrant
        returns (uint256 compositeKey)
    {
        if (decisionHash == 0) revert ZeroDecisionHash();

        compositeKey = _poseidon2(decisionHash, contextHash);

        if (fingerprints[compositeKey].registeredAt != 0) {
            revert FingerprintAlreadyExists(compositeKey);
        }

        fingerprints[compositeKey] = FingerprintEntry({
            decisionHash:        decisionHash,
            contextHash:         contextHash,
            compositeKey:        compositeKey,
            slashedAgentTokenId: slashedAgentTokenId,
            slashAmount:         type(uint256).max, // Max = permanent severity
            registeredAt:        block.timestamp,
            expiresAt:           0, // 0 = never expires
            tier:                BlacklistTier.PERMANENT,
            expired:             false
        });

        allFingerprintKeys.push(compositeKey);
        hardBlacklistSize++;

        emit FingerprintRegistered(
            compositeKey,
            decisionHash,
            slashedAgentTokenId,
            BlacklistTier.PERMANENT,
            type(uint256).max,
            0
        );

        _emitCrossChainSync(BlacklistTier.PERMANENT);
        return compositeKey;
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  SMT ROOT MANAGEMENT
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * @notice  Update the on-chain SMT root after the off-chain tree is modified.
     * @dev     Called by VaccineManager.ts (off-chain keeper) after:
     *            (a) A new fingerprint is inserted into the SMT
     *            (b) Expired fingerprints are pruned from the SMT
     *
     *          The keeper computes the new root using sparse-merkle-tree
     *          with Poseidon hashing, then calls this function.
     *
     *          SECURITY: Only authorised registrars can update the root.
     *          Production: add a ZK proof that the new root is a valid SMT root
     *          containing all expected entries (root-of-roots pattern).
     *
     * @param tier     Which blacklist root to update
     * @param newRoot  New SMT root (computed off-chain by VaccineManager)
     */
    function updateBlacklistRoot(
        BlacklistTier tier,
        uint256 newRoot
    )
        external
        onlyAuthorizedRegistrar
        whenNotPaused
    {
        uint256 oldRoot;
        uint256 size;

        if (tier == BlacklistTier.HARD || tier == BlacklistTier.PERMANENT) {
            oldRoot = hardBlacklistRoot;
            hardBlacklistRoot = newRoot;
            size = hardBlacklistSize;
        } else if (tier == BlacklistTier.SOFT) {
            oldRoot = softBlacklistRoot;
            softBlacklistRoot = newRoot;
            size = softBlacklistSize;
        } else {
            oldRoot = researchBlacklistRoot;
            researchBlacklistRoot = newRoot;
            size = allFingerprintKeys.length;
        }

        rootUpdateNonce++;

        emit BlacklistRootUpdated(tier, oldRoot, newRoot, rootUpdateNonce, size);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ZK NON-MEMBERSHIP PROOF VERIFICATION
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * @notice  Verify a ZK non-membership proof from vaccine.circom.
     * @dev     This is the CORE FUNCTION called by CognitionVerifier.sol before
     *          every transaction approval.
     *
     *          FLOW:
     *          1. Check the proof hasn't been used before (nullifier set)
     *          2. Check the blacklistRoot in the proof matches current on-chain root
     *          3. Call VaccineVerifier.verifyProof() (Groth16 pairing check)
     *          4. If all pass: mark proof as used, emit event, return true
     *          5. If any fail: revert with specific error
     *
     *          EMPTY TREE FAST PATH:
     *          If hardBlacklistRoot == 0 (no agents have been slashed yet),
     *          skip the ZK proof entirely. This saves ~230k gas for all early
     *          transactions and is cryptographically sound (empty SMT root = 0).
     *
     * @param decisionHash  Poseidon(post[0..7]) — public input from relu.circom
     * @param proofA        Groth16 proof component A (from vaccine.circom prover)
     * @param proofB        Groth16 proof component B
     * @param proofC        Groth16 proof component C
     * @return cleared      True if the agent's cognition passes vaccine check
     */
    function verifyNonMembership(
        uint256    decisionHash,
        uint256[2] calldata proofA,
        uint256[2][2] calldata proofB,
        uint256[2] calldata proofC
    )
        external
        whenNotPaused
        nonReentrant
        returns (bool cleared)
    {
        // ── FAST PATH: empty blacklist ─────────────────────────────────────
        // Before any slashes occur, the hard blacklist root is 0.
        // An empty SMT trivially contains nothing — skip ZK proof entirely.
        if (hardBlacklistRoot == 0) {
            emit VaccineProofVerified(
                msg.sender,
                decisionHash,
                0,
                bytes32(0)
            );
            return true;
        }

        // ── Proof nullifier ────────────────────────────────────────────────
        // Prevents the same proof being replayed across multiple transactions.
        // Unlike CognitionVerifier.usedProofs (which uses keccak of full proof bytes),
        // here we use keccak(proofA, proofB, proofC, decisionHash, rootNonce)
        // to bind the proof to the current root state.
        bytes32 proofNullifier = keccak256(
            abi.encodePacked(proofA, proofB, proofC, decisionHash, rootUpdateNonce)
        );

        if (usedVaccineProofs[proofNullifier]) {
            revert ProofAlreadyUsed(proofNullifier);
        }

        // ── Public inputs for vaccine.circom ──────────────────────────────
        // Circuit: component main {public [blacklistRoot, decisionHash]} = VaccineProof(20)
        // Public signals order: [blacklistRoot, decisionHash]
        uint256[2] memory pubSignals;
        pubSignals[0] = hardBlacklistRoot;
        pubSignals[1] = decisionHash;

        // ── Groth16 pairing check ──────────────────────────────────────────
        bool valid = vaccineVerifier.verifyProof(proofA, proofB, proofC, pubSignals);

        if (!valid) {
            emit VaccineProofRejected(
                msg.sender,
                decisionHash,
                "Groth16 verification failed - possible blacklist match"
            );
            revert InvalidProof();
        }

        // ── Mark proof as used ─────────────────────────────────────────────
        usedVaccineProofs[proofNullifier] = true;

        emit VaccineProofVerified(
            msg.sender,
            decisionHash,
            hardBlacklistRoot,
            proofNullifier
        );

        return true;
    }

    /**
     * @notice  Quick on-chain check: is a raw decisionHash directly in our
     *          mapping (without ZK proof)? Used for SOFT blacklist warnings.
     * @dev     Does NOT replace ZK proof for HARD blacklist enforcement.
     *          Only iterates the soft list (reputation penalties, not blocking).
     *          Returns the tier and expiry timestamp.
     */
    function checkSoftBlacklist(
        uint256 decisionHash,
        uint256 contextHash
    )
        external
        view
        returns (bool isSoftBlacklisted, uint256 expiresAt)
    {
        uint256 compositeKey = _poseidon2(decisionHash, contextHash);
        FingerprintEntry storage entry = fingerprints[compositeKey];

        if (entry.registeredAt == 0) return (false, 0);
        if (entry.expired) return (false, 0);
        if (entry.expiresAt != 0 && block.timestamp > entry.expiresAt) return (false, 0);
        if (entry.tier != BlacklistTier.SOFT) return (false, 0);

        return (true, entry.expiresAt);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  FINGERPRINT EXPIRY & PRUNING
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * @notice  Mark expired fingerprints as inactive.
     * @dev     Called by VaccineManager.ts keeper. After this call, the keeper
     *          rebuilds the off-chain SMT without expired entries and submits
     *          the new root via updateBlacklistRoot().
     *
     *          Gas cost: O(n) — in production, use Merkle-based lazy pruning
     *          or process in batches. Bounded by MAX_BLACKLIST_SIZE.
     *
     * @param compositeKeys  Array of composite keys to check for expiry
     * @return expiredCount  Number of entries that were expired
     */
    function pruneExpiredFingerprints(
        uint256[] calldata compositeKeys
    )
        external
        onlyAuthorizedRegistrar
        returns (uint256 expiredCount)
    {
        for (uint256 i = 0; i < compositeKeys.length; i++) {
            uint256 key = compositeKeys[i];
            FingerprintEntry storage entry = fingerprints[key];

            if (entry.registeredAt == 0) continue;
            if (entry.expired) continue;
            if (entry.tier == BlacklistTier.PERMANENT) {
                revert PermanentFingerprintCannotExpire(key);
            }

            if (entry.expiresAt != 0 && block.timestamp > entry.expiresAt) {
                entry.expired = true;
                expiredCount++;

                if (entry.tier == BlacklistTier.HARD) {
                    hardBlacklistSize--;
                } else {
                    softBlacklistSize--;
                }

                emit FingerprintExpired(key, entry.decisionHash, entry.tier);
            }
        }

        return expiredCount;
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  VIEW FUNCTIONS
    // ═══════════════════════════════════════════════════════════════════════

    function getFingerprint(uint256 compositeKey)
        external
        view
        returns (FingerprintEntry memory)
    {
        return fingerprints[compositeKey];
    }

    function getAllFingerprintKeys() external view returns (uint256[] memory) {
        return allFingerprintKeys;
    }

    function getFingerprintCount() external view returns (uint256 hard, uint256 soft, uint256 total) {
        return (hardBlacklistSize, softBlacklistSize, allFingerprintKeys.length);
    }

    function isBlacklistEmpty() external view returns (bool) {
        return hardBlacklistRoot == 0 && hardBlacklistSize == 0;
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ADMIN
    // ═══════════════════════════════════════════════════════════════════════

    function setVaccineVerifier(address _verifier) external onlyOwner {
        vaccineVerifier = IVaccineVerifier(_verifier);
    }

    function addAuthorizedRegistrar(address registrar) external onlyOwner {
        authorizedRegistrars[registrar] = true;
    }

    function removeAuthorizedRegistrar(address registrar) external onlyOwner {
        authorizedRegistrars[registrar] = false;
    }

    function pause() external onlyOwner { _pause(); }
    function unpause() external onlyOwner { _unpause(); }

    // ═══════════════════════════════════════════════════════════════════════
    //  INTERNAL HELPERS
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * @dev  On-chain Poseidon(2) approximation using keccak256.
     *       IMPORTANT: In production, replace with actual Poseidon2 precompile
     *       or call a deployed PoseidonHasher contract (from circomlibjs).
     *       The off-chain SMT uses circomlibjs Poseidon — these MUST match.
     *       Using keccak256 here as a placeholder that maintains the interface.
     *       The ZK circuit enforces the correct Poseidon computation internally.
     *
     *       Replacement: deploy contracts/utils/PoseidonHasher.sol (from poseidon-solidity)
     *       and call: IPoseidon(poseidonHasher).poseidon([a, b])
     */
    function _poseidon2(uint256 a, uint256 b) internal pure returns (uint256) {
        // TODO: Replace with on-chain Poseidon2 call for production
        // For hackathon: keccak serves the same structural purpose
        return uint256(keccak256(abi.encodePacked(a, b)));
    }

    /**
     * @dev  Emit event for Layer 6C cross-chain sentinel to pick up.
     *       VaccineManager.ts listens for CrossChainSyncRequired and
     *       calls sentinel.ts → CrossChainIdentity.sol → LayerZero lzSend().
     */
    function _emitCrossChainSync(BlacklistTier tier) internal {
        uint256 root = tier == BlacklistTier.SOFT ? softBlacklistRoot : hardBlacklistRoot;
        bytes32 syncId = keccak256(abi.encodePacked(root, block.timestamp, rootUpdateNonce));

        emit CrossChainSyncRequired(
            tier,
            root,
            allFingerprintKeys.length,
            syncId
        );
    }
}
