/**
 * scripts/deploy-nexus.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Deploys the full Guardian Nexus stack with REAL ZK verification.
 *
 * Deployment order:
 *   1. Groth16Verifier      — pairing verifier (generated by zk-setup.ts)
 *   2. CognitionVerifier    — wraps Groth16Verifier with commitment + replay logic
 *   3. AgentRegistry        — ERC-721 agent identity
 *   4. InsurancePool        — staking + slashing
 *   5. UnderwriterDAO       — recursive agent insurance DAO
 *   6. AgentGuardian        — main governance, wires everything together
 *
 * Usage:
 *   npx hardhat run scripts/deploy-nexus.ts --network arcTestnet
 *   npx hardhat run scripts/deploy-nexus.ts --network arcMainnet
 * ─────────────────────────────────────────────────────────────────────────────
 */

import pkg from "hardhat";
const { ethers } = pkg;
import * as fs    from "fs";
import * as path  from "path";
import * as url   from "url";

const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
    const [deployer] = await ethers.getSigners();
    const network    = await ethers.provider.getNetwork();

    console.log("═══════════════════════════════════════════════════");
    console.log(" Guardian Nexus — ZK Deployment");
    console.log("═══════════════════════════════════════════════════");
    console.log(` Network  : ${network.name} (chainId: ${network.chainId})`);
    console.log(` Deployer : ${deployer.address}`);
    console.log(` Balance  : ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ARC`);
    console.log("═══════════════════════════════════════════════════\n");

    // ── 1. Groth16Verifier ───────────────────────────────────────────────────
    console.log("[1/5] Deploying Groth16Verifier...");
    const Groth16Verifier = await ethers.getContractFactory("Groth16Verifier");
    const groth16Verifier = await Groth16Verifier.deploy();
    await groth16Verifier.waitForDeployment();
    const groth16Address  = await groth16Verifier.getAddress();
    console.log(`      ✓ Groth16Verifier : ${groth16Address}`);

    // ── 2. CognitionVerifier (needs AgentGuardian address — use address(0) then update) ──
    //    We deploy with a placeholder then set the real guardian after step 5.
    //    Alternative: deploy a factory or use a 2-phase init. We use the 2-phase approach.
    console.log("[2/5] Deploying CognitionVerifier (pre-guardian)...");
    const CognitionVerifier = await ethers.getContractFactory("CognitionVerifier");
    // Pass deployer as temporary agentGuardian — we'll wire the real one next
    const cognitionVerifier = await CognitionVerifier.deploy(
        groth16Address,
        deployer.address  // temporary; updated after guardian deploys
    );
    await cognitionVerifier.waitForDeployment();
    const cognitionAddress  = await cognitionVerifier.getAddress();
    console.log(`      ✓ CognitionVerifier : ${cognitionAddress}`);

    // ── 3. AgentRegistry ────────────────────────────────────────────────────
    console.log("[3/6] Deploying AgentRegistry...");
    const AgentRegistry = await ethers.getContractFactory("AgentRegistry");
    const agentRegistry = await AgentRegistry.deploy(deployer.address);
    await agentRegistry.waitForDeployment();
    const registryAddress = await agentRegistry.getAddress();
    console.log(`      ✓ AgentRegistry : ${registryAddress}`);

    // ── 4. InsurancePool ────────────────────────────────────────────────────
    console.log("[4/6] Deploying InsurancePool...");
    const InsurancePool = await ethers.getContractFactory("InsurancePool");
    const insurancePool = await InsurancePool.deploy(registryAddress);
    await insurancePool.waitForDeployment();
    const poolAddress   = await insurancePool.getAddress();
    console.log(`      ✓ InsurancePool : ${poolAddress}`);

    // ── 5. UnderwriterDAO ────────────────────────────────────────────────────
    console.log("[5/6] Deploying UnderwriterDAO...");
    const UnderwriterDAO = await ethers.getContractFactory("UnderwriterDAO");
    const underwriterDAO = await UnderwriterDAO.deploy(
        registryAddress,
        poolAddress
    );
    await underwriterDAO.waitForDeployment();
    const underwriterDAOAddress = await underwriterDAO.getAddress();
    console.log(`      ✓ UnderwriterDAO : ${underwriterDAOAddress}`);

    // Wire UnderwriterDAO to AgentRegistry
    console.log("      Wiring UnderwriterDAO to AgentRegistry...");
    await agentRegistry.setUnderwriterDAO(underwriterDAOAddress);
    console.log(`      ✓ AgentRegistry.setUnderwriterDAO() called`);

    // ── 6. AgentGuardian ────────────────────────────────────────────────────
    console.log("[6/6] Deploying AgentGuardian...");
    const AgentGuardian = await ethers.getContractFactory("AgentGuardian");
    // Deploy MockUSDC for testing if not already deployed
    const MockUSDC = await ethers.getContractFactory("MockUSDC");
    const mockUSDC = await MockUSDC.deploy(1000000 * 10**6); // 1M USDC
    await mockUSDC.waitForDeployment();
    const usdcAddress = await mockUSDC.getAddress();
    console.log(`      ✓ MockUSDC : ${usdcAddress}`);
    
    const agentGuardian = await AgentGuardian.deploy(
        usdcAddress,
        registryAddress,
        cognitionAddress,
        poolAddress,
        deployer.address // treasury
    );
    await agentGuardian.waitForDeployment();
    const guardianAddress = await agentGuardian.getAddress();
    console.log(`      ✓ AgentGuardian : ${guardianAddress}`);

    // ── Wire CognitionVerifier to real AgentGuardian ─────────────────────
    // NOTE: CognitionVerifier.agentGuardian is immutable in our contract.
    // For production: deploy CognitionVerifier AFTER guardian, or make it
    // settable by owner with a one-time-use setter. For hackathon we redeploy:
    console.log("\n[re-deploy] Re-deploying CognitionVerifier with real guardian...");
    const cognitionFinal = await CognitionVerifier.deploy(
        groth16Address,
        guardianAddress    // real AgentGuardian
    );
    await cognitionFinal.waitForDeployment();
    const cognitionFinalAddress = await cognitionFinal.getAddress();
    console.log(`      ✓ CognitionVerifier (final) : ${cognitionFinalAddress}`);

    // ── Summary ──────────────────────────────────────────────────────────────
    const addresses = {
        network:            network.name,
        chainId:            network.chainId.toString(),
        deployer:           deployer.address,
        Groth16Verifier:    groth16Address,
        CognitionVerifier:  cognitionFinalAddress,
        AgentRegistry:      registryAddress,
        InsurancePool:      poolAddress,
        UnderwriterDAO:     underwriterDAOAddress,
        AgentGuardian:      guardianAddress,
        deployedAt:         new Date().toISOString(),
    };

    console.log("\n═══════════════════════════════════════════════════");
    console.log(" Deployment Complete");
    console.log("═══════════════════════════════════════════════════");
    console.log(JSON.stringify(addresses, null, 2));

    // Save to file for scripts and tests
    const outDir  = path.resolve(__dirname, "..", "deployment");
    fs.mkdirSync(outDir, { recursive: true });
    const outFile = path.join(outDir, `${network.name}-${network.chainId}.json`);
    fs.writeFileSync(outFile, JSON.stringify(addresses, null, 2));
    console.log(`\nAddresses saved to: ${outFile}`);
    console.log("\nNext: Register an agent and generate a cognition proof.");
    console.log("  npx ts-node scripts/zk-prove.ts");
}

main().catch((e) => { console.error(e); process.exit(1); });
